# Site Settings
title: Alario
description: >
  The financially savvy friend you always wish you had
baseurl: ""
url: 'http://localhost:4000'
twitter_username: alario_co
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM